language: java
sudo: false
install: true

jdk:
  - oraclejdk7

script:
  - hg --version
  - ./travis.sh
                                                                                                                                                                 
env:                                                                                                                                                             
  matrix:                                                                                                                                                        
    - RUN_ITS=false                                                                                                                                              
    - RUN_ITS=true SQ_VERSION=5.0.1                                                                                                                                
    - RUN_ITS=true SQ_VERSION=DEV

cache:
  directories:
    - '$HOME/.m2/repository'

notifications:
  email: false
