language: java
sudo: false
install: true

jdk:
  - oraclejdk7

addons:
  apt:
    packages:
    - mercurial 

script:
  - hg --version
  - mvn verify -B -e -V

env:                                                                                                                                                             
  matrix:                                                                                                                                                        
    - TEST=CI

cache:
  directories:
    - '$HOME/.m2/repository'

notifications:
  email: false
