name: maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Mercurial
      run: sudo apt-get update && sudo apt-get install -y mercurial
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build
      run: mvn -B package
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v4
      with:
        name: plugin
        path: '**/target/sonar*.jar'
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@v5
